export type FriendStatus = 'SELF' | 'FRIEND' | 'SENT' | 'PENDING' | 'STRANGER'
export type RoomType = 'DM' | 'GROUP'
export type MemberRole = 'ADMIN' | 'VICE_ADMIN' | 'MEMBER'
export type MemberStatus = 'NOT_IN_GROUP' | 'ADDED' | 'SENT' | 'PENDING'
export type MessageStatus = 'SENT' | 'REVOKED'
export type MessageType = 'USER' | 'SYSTEM' | 'FORWARDED' | 'WIDGET'
export type RoomStatus = 'ACTIVE' | 'PENDING'
export type SystemAction =
  | 'ROOM_CREATED'
  | 'MEMBER_ADDED'
  | 'MEMBER_LEFT'
  | 'ROOM_NAME_CHANGED'
  | 'ROOM_AVATAR_CHANGED'
  | 'MEMBER_REMOVED'
  | 'GROUP_INVITE_ACCEPTED'
  | 'FRIEND_ACCEPTED'
