export type FriendStatus = 'SELF' | 'FRIEND' | 'SENT' | 'PENDING' | 'STRANGER'
export type RoomType = 'DM' | 'GROUP'
export type MemberRole = 'ADMIN' | 'VICE_ADMIN' | 'MEMBER'
export type MemberStatus = 'NOT_IN_GROUP' | 'ADDED' | 'SENT' | 'PENDING'
export type MessageStatus = 'SENT' | 'REVOKED'
